### ISSUE TITLE
It might not be a direct issue, but injecting the '500tech.simple-calendar' breaks app

### ISSUE THREAD

**Issue by fallesen** [500tech/angular-simple-calendar#6]
When I try injecting: '500tech.simple-calendar' the app shows a blank screen and nothing works, I have added the Whitelist plugin, which added the info in console of bower not being able to find css and js file, but I can see the files nicely in my directory, do you have any ideas what the issue could be?!

**Comment by fallesen** [comment]
I found the wrong link, so now there is no error, just a white page instead of an app when injecting the '500tech.simple-calendar'..

**Comment by newtmitch** [comment]
I just submitted a pull request to fix this issue. Hopefully it'll get merged in. https://github.com/500tech/angular-simple-calendar/pull/7
